name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Directory Permissions
      run: cd bootstrap/cache/ && rm -rf *.php

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
